"""CLI init command — generate starter ziran.yaml configuration.

Provides interactive and non-interactive modes for creating a new
ZIRAN scan configuration file in the current working directory.
"""

from __future__ import annotations

from pathlib import Path

import click
import yaml
from rich.console import Console
from rich.panel import Panel

console = Console()

_FRAMEWORKS = ["langchain", "crewai", "bedrock", "agentcore"]
_PROTOCOLS = ["rest", "openai", "mcp", "a2a"]
_DEFAULT_PHASES = [
    "reconnaissance",
    "trust_building",
    "capability_mapping",
    "vulnerability_discovery",
    "exploitation_setup",
    "initial_exploitation",
    "deep_exploitation",
    "persistence",
]

_CONFIG_FILE = "ziran.yaml"


def _generate_inprocess_config(framework: str) -> dict[str, object]:
    """Build config dict for an in-process (framework) target."""
    return {
        "framework": framework,
        "agent_path": "./my_agent.py",
        "coverage": "standard",
        "output_dir": "./ziran-results",
        "phases": _DEFAULT_PHASES,
    }


def _generate_remote_config(protocol: str) -> dict[str, object]:
    """Build config dict for a remote target."""
    return {
        "target": "./target.yaml",
        "coverage": "standard",
        "output_dir": "./ziran-results",
        "phases": _DEFAULT_PHASES,
    }


def _build_yaml_content(config: dict[str, object]) -> str:
    """Render the config dict as commented YAML."""
    lines = ["# ZIRAN Configuration", "# Generated by: ziran init", ""]

    if "framework" in config:
        lines.append("# Agent framework for in-process scanning")
        lines.append(f"framework: {config['framework']}")
        lines.append("")
        lines.append("# Path to the agent module or factory function")
        lines.append(f"agent_path: {config['agent_path']}")
    else:
        lines.append("# Target configuration file for remote scanning")
        lines.append(f"target: {config['target']}")

    lines.append("")
    lines.append("# Coverage level: quick | standard | comprehensive")
    lines.append(f"coverage: {config['coverage']}")
    lines.append("")
    lines.append("# Directory for scan results and reports")
    lines.append(f"output_dir: {config['output_dir']}")
    lines.append("")
    lines.append("# Scan phases to execute")
    phases_yaml = yaml.dump({"phases": config["phases"]}, default_flow_style=False).strip()
    lines.append(phases_yaml)
    lines.append("")

    return "\n".join(lines)


def _display_next_steps(config: dict[str, object]) -> None:
    """Show a Rich panel with next-steps guidance."""
    if "framework" in config:
        scan_cmd = (
            f"ziran scan --framework {config['framework']} --agent-path {config['agent_path']}"
        )
    else:
        scan_cmd = f"ziran scan --target {config['target']}"

    body = (
        "[bold green]Configuration created![/bold green]\n\n"
        "[bold]Next steps:[/bold]\n"
        f"  1. Edit [cyan]{_CONFIG_FILE}[/cyan] "
        "with your agent details\n"
        f"  2. Run your first scan:\n\n"
        f"     [bold cyan]{scan_cmd}[/bold cyan]\n\n"
        "  3. View results in "
        f"[cyan]{config['output_dir']}[/cyan]"
    )
    console.print(Panel(body, title="ziran init", border_style="green"))


@click.command()
@click.option(
    "--non-interactive",
    is_flag=True,
    default=False,
    help="Skip prompts and use defaults (for CI/scripts).",
)
def init(non_interactive: bool) -> None:
    """Initialize a new ZIRAN scan configuration.

    Generates a starter ziran.yaml in the current directory with
    sensible defaults. Use --non-interactive for CI pipelines.
    """
    config_path = Path.cwd() / _CONFIG_FILE

    # ── Overwrite protection ─────────────────────────────────────
    if config_path.exists():
        if non_interactive:
            console.print(
                f"[bold red]Error:[/bold red] "
                f"{_CONFIG_FILE} already exists. "
                "Remove it first or run without --non-interactive.",
            )
            raise SystemExit(1)
        if not click.confirm(f"{_CONFIG_FILE} already exists. Overwrite?"):
            console.print("Aborted — existing config preserved.")
            return

    # ── Interactive prompts or defaults ──────────────────────────
    if non_interactive:
        config = _generate_inprocess_config("langchain")
    else:
        target_type = click.prompt(
            "Target type",
            type=click.Choice(["in-process", "remote"], case_sensitive=False),
            default="in-process",
        )
        if target_type == "in-process":
            framework = click.prompt(
                "Framework",
                type=click.Choice(_FRAMEWORKS, case_sensitive=False),
                default="langchain",
            )
            config = _generate_inprocess_config(framework)
        else:
            protocol = click.prompt(
                "Protocol",
                type=click.Choice(_PROTOCOLS, case_sensitive=False),
                default="rest",
            )
            config = _generate_remote_config(protocol)

    # ── Write config ─────────────────────────────────────────────
    content = _build_yaml_content(config)
    config_path.write_text(content, encoding="utf-8")

    _display_next_steps(config)
