"""Cedar policy renderer — generates AWS Cedar forbid policies."""

from __future__ import annotations

from typing import TYPE_CHECKING

from ziran.domain.entities.policy import GuardrailPolicy, GuardrailPolicyFormat
from ziran.domain.ports.policy_renderer import PolicyRenderer

if TYPE_CHECKING:
    from ziran.domain.entities.capability import DangerousChain


class CedarRenderer(PolicyRenderer):
    """Render DangerousChain findings as Cedar forbid policies.

    Cedar is stateless, so multi-step (3+ tool) sequences cannot be
    expressed natively.  Those chains are marked as skipped.
    """

    @property
    def format(self) -> GuardrailPolicyFormat:
        return GuardrailPolicyFormat.CEDAR

    def render(
        self,
        finding: DangerousChain,
        finding_id: str,
    ) -> GuardrailPolicy:
        tools = finding.tools

        # Cedar cannot express multi-step sequences natively
        if len(tools) > 2:
            return GuardrailPolicy(
                finding_id=finding_id,
                format=GuardrailPolicyFormat.CEDAR,
                content="",
                tool_chain=list(tools),
                severity=finding.risk_level,
                skipped=True,
                skip_reason=("Cedar does not support multi-step sequence detection natively"),
            )

        tool_a = tools[0]
        tool_b = tools[1]

        lines: list[str] = [
            "// Generated by Ziran",
            f"// Finding: {finding_id}",
            "// NOTE: Cedar is stateless. The runtime gateway must track tool-call",
            "// state and pass context.previous_tool for sequence detection.",
            "forbid (",
            "    principal,",
            '    action == Action::"tool_call",',
            f'    resource == Tool::"{tool_b}"',
            ") when {",
            f'    context.previous_tool == "{tool_a}"',
            "};",
        ]

        content = "\n".join(lines) + "\n"

        return GuardrailPolicy(
            finding_id=finding_id,
            format=GuardrailPolicyFormat.CEDAR,
            content=content,
            tool_chain=list(tools),
            severity=finding.risk_level,
        )
