"""Colang 2.0 policy renderer — generates NeMo Guardrails flows."""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from ziran.domain.entities.policy import GuardrailPolicy, GuardrailPolicyFormat
from ziran.domain.ports.policy_renderer import PolicyRenderer

if TYPE_CHECKING:
    from ziran.domain.entities.capability import DangerousChain


def _sanitize(name: str) -> str:
    """Turn a string into a safe Colang identifier fragment."""
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


class ColangRenderer(PolicyRenderer):
    """Render DangerousChain findings as Colang 2.0 flows."""

    @property
    def format(self) -> GuardrailPolicyFormat:
        return GuardrailPolicyFormat.COLANG

    def render(
        self,
        finding: DangerousChain,
        finding_id: str,
    ) -> GuardrailPolicy:
        tools = finding.tools
        chain_label = " \u2192 ".join(tools)
        vuln = finding.vulnerability_type
        sanitized_chain = "_".join(_sanitize(t) for t in tools)
        flow_name = f"block_{_sanitize(vuln)}_{sanitized_chain}"

        lines: list[str] = [
            "# Generated by Ziran",
            f"# Finding: {finding_id}",
            f"define flow {flow_name}",
        ]

        for idx, tool in enumerate(tools):
            var = f"$step{idx}"
            lines.append(
                f'    match ToolCall(tool_name="{tool}") as {var}',
            )

        blocked_msg = f"Blocked: {chain_label} sequence is forbidden (Ziran {finding_id})."
        lines.append(f'    await bot say "{blocked_msg}"')
        lines.append("    abort")

        content = "\n".join(lines) + "\n"

        return GuardrailPolicy(
            finding_id=finding_id,
            format=GuardrailPolicyFormat.COLANG,
            content=content,
            tool_chain=list(tools),
            severity=finding.risk_level,
        )
