"""Invariant DSL renderer — generates Invariant guardrail rules."""

from __future__ import annotations

from typing import TYPE_CHECKING

from ziran.domain.entities.policy import GuardrailPolicy, GuardrailPolicyFormat
from ziran.domain.ports.policy_renderer import PolicyRenderer

if TYPE_CHECKING:
    from ziran.domain.entities.capability import DangerousChain


class InvariantRenderer(PolicyRenderer):
    """Render DangerousChain findings as Invariant DSL rules."""

    @property
    def format(self) -> GuardrailPolicyFormat:
        return GuardrailPolicyFormat.INVARIANT

    def render(
        self,
        finding: DangerousChain,
        finding_id: str,
    ) -> GuardrailPolicy:
        tools = finding.tools
        chain_label = " \u2192 ".join(tools)
        vuln = finding.vulnerability_type

        lines: list[str] = [
            "# Generated by Ziran",
            f"# Finding: {finding_id}",
        ]

        msg = f"Ziran finding {finding_id}: {chain_label} ({vuln})"
        lines.append(
            f'raise PolicyViolation("{msg}") if:',
        )

        # Variable declarations for each tool call
        for idx, tool in enumerate(tools):
            var = chr(ord("a") + idx)
            lines.append(
                f'    call_{var}: ToolCall(function="{tool}")',
            )

        # Temporal ordering constraints for consecutive pairs
        for idx in range(len(tools) - 1):
            var_curr = chr(ord("a") + idx)
            var_next = chr(ord("a") + idx + 1)
            lines.append(
                f"    call_{var_curr} -> call_{var_next}",
            )

        content = "\n".join(lines) + "\n"

        return GuardrailPolicy(
            finding_id=finding_id,
            format=GuardrailPolicyFormat.INVARIANT,
            content=content,
            tool_chain=list(tools),
            severity=finding.risk_level,
        )
