"""Rego policy renderer — generates Open Policy Agent modules."""

from __future__ import annotations

from typing import TYPE_CHECKING

from ziran.domain.entities.policy import GuardrailPolicy, GuardrailPolicyFormat
from ziran.domain.ports.policy_renderer import PolicyRenderer

if TYPE_CHECKING:
    from ziran.domain.entities.capability import DangerousChain


class RegoRenderer(PolicyRenderer):
    """Render DangerousChain findings as Rego deny rules."""

    @property
    def format(self) -> GuardrailPolicyFormat:
        return GuardrailPolicyFormat.REGO

    def render(
        self,
        finding: DangerousChain,
        finding_id: str,
    ) -> GuardrailPolicy:
        tools = finding.tools
        chain_label = " \u2192 ".join(tools)
        vuln = finding.vulnerability_type

        lines: list[str] = [
            "# Generated by Ziran",
            f"# Finding: {finding_id}",
            f"# Chain: {chain_label}",
            f"# Severity: {finding.risk_level}",
            "package ziran.guardrails",
            "",
            "deny[msg] {",
            "    some i",
        ]

        # Add tool-match clauses for each consecutive pair
        for idx, tool in enumerate(tools):
            offset = f"i + {idx}" if idx > 0 else "i"
            lines.append(
                f'    input.trace[{offset}].tool == "{tool}"',
            )

        msg_text = f"Ziran finding {finding_id}: {chain_label} ({vuln})"
        lines.append(f'    msg := "{msg_text}"')
        lines.append("}")

        content = "\n".join(lines) + "\n"

        return GuardrailPolicy(
            finding_id=finding_id,
            format=GuardrailPolicyFormat.REGO,
            content=content,
            tool_chain=list(tools),
            severity=finding.risk_level,
        )
